apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../k8s

namespace: rclob-staging

resources:
  - hpa.yaml

patches:
  - target:
      kind: Deployment
      name: rclob
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: debug

images:
  - name: rclob
    newName: registry.example.com/rclob
    newTag: staging-latest

configMapGenerator:
  - name: rclob-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
